/**
 * Extract mount spell IDs from spell.csv
 * Usage: node scripts/extract-mounts.js <path/to/spell.csv>
 * Outputs: src/shared/constants/mount-spell-ids.ts
 *
 * AzerothCore spell.csv typically has these columns:
 * ID, Category, DispelType, Mechanic, Attributes, ...
 * We look for spells with EFFECT_1 = 6 (SPELL_EFFECT_APPLY_AURA)
 * and AURA_1 = 78 (SPELL_AURA_MOUNTED) or similar mount-related flags.
 *
 * For simplicity, this script parses the CSV and generates a TypeScript constant.
 */

const fs = require('fs');
const path = require('path');

const INPUT_PATH = process.argv[2];
const OUTPUT_PATH = path.resolve(__dirname, '../backend/src/shared/constants/mount-spell-ids.ts');

if (!INPUT_PATH) {
  console.error('Usage: node extract-mounts.js <path/to/spell.csv>');
  process.exit(1);
}

if (!fs.existsSync(INPUT_PATH)) {
  console.error(`File not found: ${INPUT_PATH}`);
  process.exit(1);
}

console.log(`Reading ${INPUT_PATH}...`);
const content = fs.readFileSync(INPUT_PATH, 'utf-8');
const lines = content.split(/\r?\n/).filter((l) => l.trim());

const header = lines[0].split(',').map((h) => h.trim().replace(/^"|"$/g, ''));
const idIndex = header.indexOf('ID');
const effect1Index = header.indexOf('Effect_1');
const aura1Index = header.indexOf('EffectAura_1');

if (idIndex === -1) {
  console.error('Column "ID" not found in CSV header.');
  process.exit(1);
}

const mountIds = [];
const SPELL_EFFECT_APPLY_AURA = 6;
const SPELL_AURA_MOUNTED = 78;

for (let i = 1; i < lines.length; i++) {
  const cols = lines[i].split(',').map((c) => c.trim().replace(/^"|"$/g, ''));
  const id = parseInt(cols[idIndex], 10);
  const effect1 = effect1Index >= 0 ? parseInt(cols[effect1Index], 10) : NaN;
  const aura1 = aura1Index >= 0 ? parseInt(cols[aura1Index], 10) : NaN;

  if (
    !Number.isNaN(id) &&
    effect1 === SPELL_EFFECT_APPLY_AURA &&
    aura1 === SPELL_AURA_MOUNTED
  ) {
    mountIds.push(id);
  }
}

mountIds.sort((a, b) => a - b);

const tsContent = `// Auto-generated by scripts/extract-mounts.js
// Do not edit manually. Total: ${mountIds.length} mount spell IDs.

export const MOUNT_SPELL_IDS: number[] = [
${mountIds.map((id) => `  ${id},`).join('\n')}
];
`;

fs.writeFileSync(OUTPUT_PATH, tsContent);
console.log(`Generated ${OUTPUT_PATH} with ${mountIds.length} mount spell IDs.`);
